#!/usr/bin/env bash
# install_service_deck.sh - Mad Max offline server: systemd service installer for Steam Deck
# Generated by madmax-2015-offline @ __LAN_IP__
#
# Usage (must be run as root):
#   curl -o install_service_deck.sh http://__LAN_IP__:__HTTP_PORT__/provision/deck/service && sudo bash install_service_deck.sh
#
# What this script does:
#   1. Locates the madmax-2015-offline project directory automatically
#   2. Writes /etc/systemd/system/madmax-offline.service (runs main.py as root)
#   3. Writes a polkit rule so the 'deck' user can start/stop the service without sudo
#   4. ExecStartPost: sets DNS on the active network connection to this proxy
#   5. ExecStopPost:  restores auto-DNS when the service stops (including shutdown)
#   6. Registers the service with systemd (does NOT enable autostart, does NOT start it)
#      The service starts only when launched via Steam Launch Options.
#
# To uninstall:
#   sudo systemctl stop madmax-offline
#   sudo rm /etc/systemd/system/madmax-offline.service
#   sudo rm /etc/polkit-1/rules.d/50-madmax-offline.rules
#   sudo systemctl daemon-reload

set -euo pipefail

PROXY_IP="__LAN_IP__"
PYTHON_BIN="$(command -v python3 || echo /usr/bin/python3)"
SERVICE_NAME="madmax-offline"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
POLKIT_RULE="/etc/polkit-1/rules.d/50-${SERVICE_NAME}.rules"

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: Run this script with sudo." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Auto-detect PROJECT_DIR: search common locations for main.py
# ---------------------------------------------------------------------------
_find_project_dir() {
    local candidates=(
        "/home/deck/madmax-2015-offline"
        "/home/deck/Documents/madmax-2015-offline"
        "/home/deck/Downloads/madmax-2015-offline"
        "$HOME/madmax-2015-offline"
        "$HOME/Documents/madmax-2015-offline"
    )
    for d in "${candidates[@]}"; do
        [ -f "$d/main.py" ] && echo "$d" && return 0
    done
    return 1
}

PROJECT_DIR="$(_find_project_dir || true)"

if [ -z "$PROJECT_DIR" ]; then
    echo "ERROR: Could not find madmax-2015-offline/main.py in any expected location." >&2
    echo "" >&2
    echo "  Searched:" >&2
    echo "    /home/deck/madmax-2015-offline" >&2
    echo "    /home/deck/Documents/madmax-2015-offline" >&2
    echo "    /home/deck/Downloads/madmax-2015-offline" >&2
    echo "    \$HOME/madmax-2015-offline" >&2
    echo "    \$HOME/Documents/madmax-2015-offline" >&2
    echo "" >&2
    echo "  If your install path differs, edit this script and add:" >&2
    echo "    PROJECT_DIR=\"/path/to/madmax-2015-offline\"" >&2
    echo "  just below the 'set -euo pipefail' line, then re-run." >&2
    exit 1
fi

echo "=== Mad Max Offline - Service Installer ==="
echo "  Project dir  : ${PROJECT_DIR}"
echo "  Python       : ${PYTHON_BIN}"
echo "  Proxy IP     : ${PROXY_IP}"
echo ""

steamos-readonly disable 2>/dev/null || true

cat > "${SERVICE_FILE}" << UNIT
[Unit]
Description=Mad Max 2015 - Offline Server Emulator
# Start after network is up.
After=network-online.target NetworkManager.service
Wants=network-online.target
# Stop before NetworkManager on shutdown so ExecStopPost (DNS restore) can
# still reach nmcli while NetworkManager is still running.
Before=network.target
DefaultDependencies=no

[Service]
Type=simple
User=root
WorkingDirectory=${PROJECT_DIR}
ExecStart=${PYTHON_BIN} ${PROJECT_DIR}/main.py

# Give the server 2 s to bind its ports, then point DNS at it.
# Fallback DNS (__UPSTREAM_DNS__) comes from UPSTREAM_DNS in config.py.
ExecStartPost=/usr/bin/bash -c '\
    sleep 2; \
    CONN=\$(nmcli -t -f NAME,TYPE con show --active 2>/dev/null | grep ":wifi\$" | cut -d: -f1 | head -1); \
    [ -z "\$CONN" ] && CONN=\$(nmcli -t -f NAME con show --active 2>/dev/null | head -1 | cut -d: -f1); \
    [ -z "\$CONN" ] && { echo "[madmax-offline] No active connection found, DNS not set."; exit 0; }; \
    nmcli con mod "\$CONN" ipv4.dns "${PROXY_IP} __UPSTREAM_DNS__" ipv4.ignore-auto-dns yes && \
    nmcli con up "\$CONN" && \
    echo "[madmax-offline] DNS -> ${PROXY_IP} (__UPSTREAM_DNS__ fallback) on: \$CONN"'

# Restore automatic DNS when the service stops — runs on both normal stop
# and system shutdown (Before=network.target ensures NM is still up).
ExecStopPost=/usr/bin/bash -c '\
    CONN=\$(nmcli -t -f NAME,TYPE con show --active 2>/dev/null | grep ":wifi\$" | cut -d: -f1 | head -1); \
    [ -z "\$CONN" ] && CONN=\$(nmcli -t -f NAME con show --active 2>/dev/null | head -1 | cut -d: -f1); \
    [ -z "\$CONN" ] && exit 0; \
    nmcli con mod "\$CONN" ipv4.dns "" ipv4.ignore-auto-dns no && \
    nmcli con up "\$CONN" && \
    echo "[madmax-offline] DNS restored (auto) on connection: \$CONN"'

# No automatic restart — the service is started on demand by Steam.
StandardOutput=journal
StandardError=journal
SyslogIdentifier=madmax-offline

[Install]
# Not enabled for autostart — started only via Steam Launch Options:
#   systemctl start madmax-offline ; %command%
WantedBy=multi-user.target
UNIT

echo "[1/3] Service file written: ${SERVICE_FILE}"

# ---------------------------------------------------------------------------
# polkit rule: allow the 'deck' user to start/stop/restart this service
# without a password prompt.  Only covers madmax-offline.service.
# ---------------------------------------------------------------------------
mkdir -p /etc/polkit-1/rules.d
cat > "${POLKIT_RULE}" << 'POLKIT'
polkit.addRule(function(action, subject) {
    if (action.id === "org.freedesktop.systemd1.manage-units" &&
        action.lookup("unit") === "madmax-offline.service" &&
        (action.lookup("verb") === "start"   ||
         action.lookup("verb") === "stop"    ||
         action.lookup("verb") === "restart" ||
         action.lookup("verb") === "reload-or-restart") &&
        subject.user === "deck")
    {
        return polkit.Result.YES;
    }
});
POLKIT

echo "[2/3] Polkit rule written: ${POLKIT_RULE}"
echo "      The 'deck' user can now start/stop the service without sudo."

systemctl daemon-reload

echo "[3/3] Service registered (no autostart)."
echo "      It starts only when you launch Mad Max from Steam."

steamos-readonly enable 2>/dev/null || true

echo ""
echo "=== Done! ==="
echo ""
echo "Steam Launch Options (set once in Steam game properties):"
echo "  systemctl start ${SERVICE_NAME} ; %command%"
echo ""
echo "Other useful commands:"
echo "  systemctl status ${SERVICE_NAME}          # no sudo needed"
echo "  journalctl -u ${SERVICE_NAME} -f          # no sudo needed"
echo "  systemctl stop ${SERVICE_NAME}            # no sudo needed"
