#!/usr/bin/env bash
# setup_deck.sh - Mad Max server emulator setup for Steam Deck (SteamOS + Proton)
# Generated by local_proxy.py @ __LAN_IP__
#
# Usage:
#   curl -o setup_deck.sh http://__LAN_IP__:__HTTP_PORT__/provision/deck && bash setup_deck.sh

set -e
PROXY_IP="__LAN_IP__"
WINE="$HOME/.local/share/Steam/steamapps/common/__WINE_PROTON_VER__/files/bin/wine"
WINEPREFIX="$HOME/.local/share/Steam/steamapps/compatdata/__GAME_APP_ID__/pfx"

echo "=== Mad Max - Steam Deck Setup ==="
echo "Proxy IP: $PROXY_IP"

echo "[1/4] Writing CA certificate..."
cat > /tmp/localproxy_ca.crt << 'CERTEOF'
__CA_PEM__
CERTEOF
cp /tmp/localproxy_ca.crt ~/ca.crt
echo "      Saved to ~/ca.crt"

echo "[2/4] Installing CA to system trust bundle (requires sudo)..."
if sudo steamos-readonly disable 2>/dev/null; then
    sudo cp /tmp/localproxy_ca.crt /etc/ssl/certs/localproxy_ca.crt
    sudo bash -c 'cat /etc/ssl/certs/localproxy_ca.crt >> /etc/ssl/certs/ca-certificates.crt'
    sudo steamos-readonly enable
    echo "      Added to /etc/ssl/certs/ca-certificates.crt"
else
    echo "      WARNING: steamos-readonly failed - skipping system bundle"
fi

echo "[3/4] Installing CA to Wine/Proton registry..."

python3 << 'PYEOF'
import os
import glob
import re
import struct
import subprocess
import sys

ca_path = os.path.expanduser("~/ca.crt")
wine    = os.path.expanduser("~/.local/share/Steam/steamapps/common/__WINE_PROTON_VER__/files/bin/wine")


def find_wineprefix(app_id: str) -> str:
    candidates = [
        os.path.expanduser(f"~/.local/share/Steam/steamapps/compatdata/{app_id}/pfx"),
        os.path.expanduser(f"~/.steam/steam/steamapps/compatdata/{app_id}/pfx"),
    ]
    candidates += glob.glob(f"/run/media/deck/*/steamapps/compatdata/{app_id}/pfx")
    for candidate in candidates:
        if os.path.exists(os.path.join(candidate, "system.reg")):
            return candidate
    existing = [candidate for candidate in candidates if os.path.isdir(candidate)]
    if existing:
        return existing[0]
    raise FileNotFoundError(f"Could not find compatdata/__GAME_APP_ID__/pfx in Steam libraries: {candidates}")


try:
    wprefix = find_wineprefix("__GAME_APP_ID__")
    print(f"      Using prefix: {wprefix}")
except FileNotFoundError as exc:
    print(f"      ERROR: {exc}", file=sys.stderr)
    sys.exit(1)

if not os.path.exists(wine):
    candidates  = glob.glob(os.path.expanduser("~/.local/share/Steam/steamapps/common/Proton*/files/bin/wine"))
    candidates += glob.glob("/run/media/deck/*/steamapps/common/Proton*/files/bin/wine")
    if candidates:
        wine = sorted(candidates)[-1]
        print(f"      Using Wine: {wine}")
    else:
        print("      ERROR: Could not find Wine/Proton installation", file=sys.stderr)
        sys.exit(1)

os.makedirs(wprefix, exist_ok=True)
env = dict(os.environ, WINEPREFIX=wprefix)
wineboot = os.path.join(os.path.dirname(wine), "wineboot")
wineserver = os.path.join(os.path.dirname(wine), "wineserver")

boot_cmd = [wineboot, "-u"] if os.path.exists(wineboot) else [wine, "wineboot", "-u"]
boot = subprocess.run(boot_cmd, env=env, capture_output=True, text=True)
if boot.returncode != 0:
    print(f"      ERROR: wineboot failed: {(boot.stderr or boot.stdout)[:300]}", file=sys.stderr)
    sys.exit(1)
server_wait_cmd = [wineserver, "-w"] if os.path.exists(wineserver) else [wine, "wineserver", "-w"]
server_kill_cmd = [wineserver, "-k"] if os.path.exists(wineserver) else [wine, "wineserver", "-k"]
subprocess.run(server_wait_cmd, env=env, capture_output=True, text=True)
subprocess.run(server_kill_cmd, env=env, capture_output=True, text=True)
subprocess.run(server_wait_cmd, env=env, capture_output=True, text=True)

der = subprocess.check_output(f"openssl x509 -in {ca_path} -outform DER", shell=True)
fp  = subprocess.check_output(f"openssl x509 -in {ca_path} -noout -fingerprint -sha1", shell=True)
fp  = fp.decode().strip().split("=")[1].replace(":","")
fp_bytes = bytes.fromhex(fp)

print(f"      Fingerprint : {fp}")
print(f"      DER size    : {len(der)} bytes")

blob  = struct.pack("<III", 3,  1, 20)       + fp_bytes
blob += struct.pack("<III", 32, 1, len(der)) + der

hex_str = "".join(f"{b:02x}" for b in blob)
blob_line = '"Blob"=hex:' + ",".join(hex_str[i:i + 2] for i in range(0, len(hex_str), 2))


def upsert_reg_blob(reg_path: str, section_name: str, blob_value_line: str) -> None:
    if not os.path.exists(reg_path):
        return
    with open(reg_path, "r", encoding="utf-8", errors="surrogateescape") as handle:
        content = handle.read()

    section_header = f"[{section_name}]"
    section_pattern = re.compile(
        rf"^\[{re.escape(section_name)}\]\n(?:.*\n)*?(?=^\[|\Z)",
        re.MULTILINE,
    )
    blob_pattern = re.compile(r'^"Blob"=hex:.*$', re.MULTILINE)

    if section_pattern.search(content):
        def _replace(match: re.Match[str]) -> str:
            block = match.group(0)
            if blob_pattern.search(block):
                return blob_pattern.sub(blob_value_line, block, count=1)
            return block.rstrip("\n") + "\n" + blob_value_line + "\n"

        content = section_pattern.sub(_replace, content, count=1)
    else:
        if not content.endswith("\n"):
            content += "\n"
        content += f"\n{section_header}\n{blob_value_line}\n"

    with open(reg_path, "w", encoding="utf-8", errors="surrogateescape") as handle:
        handle.write(content)


stores = [
    ("HKLM", "Root", os.path.join(wprefix, "system.reg")),
    ("HKLM", "CA", os.path.join(wprefix, "system.reg")),
    ("HKCU", "Root", os.path.join(wprefix, "user.reg")),
    ("HKCU", "CA", os.path.join(wprefix, "user.reg")),
]

for hive, store_name, reg_file in stores:
    cert_key = fr"{hive}\Software\Microsoft\SystemCertificates\{store_name}\Certificates\{fp}"
    for key in [
        fr"{hive}\Software\Microsoft",
        fr"{hive}\Software\Microsoft\SystemCertificates",
        fr"{hive}\Software\Microsoft\SystemCertificates\{store_name}",
        fr"{hive}\Software\Microsoft\SystemCertificates\{store_name}\Certificates",
        cert_key,
    ]:
        created = subprocess.run([wine, "reg", "add", key, "/f"], env=env, capture_output=True, text=True)
        if created.returncode != 0:
            print(f"      ERROR: failed to create registry key {key}: {(created.stderr or created.stdout)[:300]}", file=sys.stderr)
            sys.exit(1)

    set_blob = subprocess.run(
        [wine, "reg", "add", cert_key, "/v", "Blob", "/t", "REG_BINARY", "/d", hex_str, "/f"],
        env=env,
        capture_output=True,
        text=True,
    )
    if set_blob.returncode != 0:
        print(f"      ERROR: failed to set Blob for {cert_key}: {(set_blob.stderr or set_blob.stdout)[:300]}", file=sys.stderr)
        sys.exit(1)

    section_name = fr"Software\\Microsoft\\SystemCertificates\\{store_name}\\Certificates\\{fp}"
    upsert_reg_blob(reg_file, section_name, blob_line)
    print(f"      OK: CA installed under key {cert_key}")

boot = subprocess.run(boot_cmd, env=env, capture_output=True, text=True)
if boot.returncode != 0:
    print(f"      ERROR: wineboot reload failed: {(boot.stderr or boot.stdout)[:300]}", file=sys.stderr)
    sys.exit(1)
subprocess.run(server_wait_cmd, env=env, capture_output=True, text=True)

for reg_file in [os.path.join(wprefix, "system.reg"), os.path.join(wprefix, "user.reg")]:
    if os.path.exists(reg_file):
        with open(reg_file, "r", encoding="utf-8", errors="surrogateescape") as handle:
            has_fp = fp in handle.read()
        print(f"      Verify {os.path.basename(reg_file)} contains fingerprint: {has_fp}")
PYEOF

echo "[4/4] Configuring DNS and Wine overrides..."

WIFI_IFACE=$(nmcli -t -f NAME,TYPE con show --active | grep ":wifi" | cut -d: -f1 | head -1)
if [ -z "$WIFI_IFACE" ]; then
    WIFI_IFACE=$(nmcli -t -f NAME con show --active | head -1)
fi
echo "      Interface: $WIFI_IFACE"

nmcli con mod "$WIFI_IFACE" ipv4.dns "$PROXY_IP 8.8.8.8"
nmcli con mod "$WIFI_IFACE" ipv4.ignore-auto-dns yes
nmcli con up "$WIFI_IFACE"
echo "      DNS set to $PROXY_IP"

python3 -c "
import subprocess, os, glob

wine    = os.path.expanduser('~/.local/share/Steam/steamapps/common/__WINE_PROTON_VER__/files/bin/wine')

def find_wineprefix(app_id: str) -> str:
    candidates = [
        os.path.expanduser(f'~/.local/share/Steam/steamapps/compatdata/{app_id}/pfx'),
        os.path.expanduser(f'~/.steam/steam/steamapps/compatdata/{app_id}/pfx'),
    ]
    candidates += glob.glob(f'/run/media/deck/*/steamapps/compatdata/{app_id}/pfx')
    for candidate in candidates:
        if os.path.exists(os.path.join(candidate, 'user.reg')):
            return candidate
    existing = [candidate for candidate in candidates if os.path.isdir(candidate)]
    if existing:
        return existing[0]
    raise FileNotFoundError(f'Could not find compatdata/__GAME_APP_ID__/pfx in Steam libraries: {candidates}')

wprefix = find_wineprefix('__GAME_APP_ID__')
print(f'      Using prefix: {wprefix}')

if not os.path.exists(wine):
    candidates  = glob.glob(os.path.expanduser('~/.local/share/Steam/steamapps/common/Proton*/files/bin/wine'))
    candidates += glob.glob('/run/media/deck/*/steamapps/common/Proton*/files/bin/wine')
    if candidates:
        wine = sorted(candidates)[-1]

os.makedirs(wprefix, exist_ok=True)
env = dict(os.environ, WINEPREFIX=wprefix)
wineboot = os.path.join(os.path.dirname(wine), 'wineboot')
wineserver = os.path.join(os.path.dirname(wine), 'wineserver')

boot_cmd = [wineboot, '-u'] if os.path.exists(wineboot) else [wine, 'wineboot', '-u']
boot = subprocess.run(boot_cmd, env=env, capture_output=True, text=True)
if boot.returncode != 0:
    raise SystemExit(f'ERROR: wineboot failed: {(boot.stderr or boot.stdout)[:300]}')
if os.path.exists(wineserver):
    subprocess.run([wineserver, '-w'], env=env, capture_output=True, text=True)

for key in [
    'HKEY_CURRENT_USER\\\\Software\\\\Wine',
    'HKEY_CURRENT_USER\\\\Software\\\\Wine\\\\DllOverrides',
]:
    created = subprocess.run([wine, 'reg', 'add', key, '/f'], env=env, capture_output=True, text=True)
    if created.returncode != 0:
        raise SystemExit(f'ERROR: failed to create {key}: {(created.stderr or created.stdout)[:300]}')

result = subprocess.run([wine, 'reg', 'add',
    'HKEY_CURRENT_USER\\\\Software\\\\Wine\\\\DllOverrides',
    '/v', 'winhttp', '/t', 'REG_SZ', '/d', 'builtin', '/f'],
    env=env, capture_output=True, text=True)
if result.returncode != 0:
    raise SystemExit(f'ERROR: failed to set winhttp override: {(result.stderr or result.stdout)[:300]}')
print('      winhttp DLL override set to: builtin')
"

echo ""
echo "=== Setup complete! ==="
echo "Make sure local_proxy.py is running on $PROXY_IP, then launch Mad Max."
echo ""
echo "To revert DNS:"
echo "  nmcli con mod \"$WIFI_IFACE\" ipv4.dns \"\" ipv4.ignore-auto-dns no && nmcli con up \"$WIFI_IFACE\""
