#!/usr/bin/env bash
# uninstall_cert_deck.sh - Remove Mad Max proxy CA from Steam Deck (SteamOS + Proton)
# Generated by madmax-2015-offline @ __LAN_IP__
#
# Usage:
#   curl -o uninstall_cert_deck.sh http://__LAN_IP__:__HTTP_PORT__/provision/deck/uninstall && bash uninstall_cert_deck.sh

set -euo pipefail

GAME_APP_ID="__GAME_APP_ID__"

echo "=== Mad Max - Steam Deck Certificate Removal ==="

# ---------------------------------------------------------------------------
# Helper: find Proton wineprefix
# ---------------------------------------------------------------------------
find_wineprefix() {
    local candidates=(
        "$HOME/.local/share/Steam/steamapps/compatdata/${GAME_APP_ID}/pfx"
        "$HOME/.steam/steam/steamapps/compatdata/${GAME_APP_ID}/pfx"
    )
    for c in "${candidates[@]}"; do
        [ -f "$c/system.reg" ] && echo "$c" && return 0
    done
    # SD card paths
    for c in /run/media/deck/*/steamapps/compatdata/"${GAME_APP_ID}"/pfx; do
        [ -f "$c/system.reg" ] && echo "$c" && return 0
    done
    return 1
}

find_wine() {
    local candidates=(
        "$HOME/.local/share/Steam/steamapps/common/__WINE_PROTON_VER__/files/bin/wine"
    )
    for c in "${candidates[@]}"; do [ -f "$c" ] && echo "$c" && return 0; done
    local found
    found=$(ls "$HOME"/.local/share/Steam/steamapps/common/Proton*/files/bin/wine 2>/dev/null \
            | sort | tail -1 || true)
    [ -n "$found" ] && echo "$found" && return 0
    for c in /run/media/deck/*/steamapps/common/Proton*/files/bin/wine; do
        [ -f "$c" ] && echo "$c" && return 0
    done
    return 1
}

# ---------------------------------------------------------------------------
# [1/3] Remove CA from system trust bundle
# ---------------------------------------------------------------------------
echo "[1/3] Removing CA from system trust bundle..."
CA_SYS="/etc/ssl/certs/localproxy_ca.crt"
if sudo steamos-readonly disable 2>/dev/null; then
    if [ -f "$CA_SYS" ]; then
        # Remove the certificate block from the bundle
        sudo python3 - "$CA_SYS" << 'PYEOF'
import sys, re, pathlib

ca_path = pathlib.Path(sys.argv[1])
bundle  = pathlib.Path("/etc/ssl/certs/ca-certificates.crt")

if ca_path.exists():
    ca_text = ca_path.read_text(encoding="utf-8", errors="replace")
    # Extract the PEM block to remove from the bundle
    pem_match = re.search(r"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----", ca_text, re.DOTALL)
    if pem_match and bundle.exists():
        bundle_text = bundle.read_text(encoding="utf-8", errors="replace")
        cleaned = bundle_text.replace(pem_match.group(0), "").strip() + "\n"
        bundle.write_text(cleaned, encoding="utf-8")
        print("      Removed from ca-certificates.crt")
    ca_path.unlink()
    print(f"      Deleted {ca_path}")
else:
    print("      Not found, skipping.")
PYEOF
    else
        echo "      Not found at $CA_SYS, skipping."
    fi
    sudo steamos-readonly enable 2>/dev/null || true
else
    echo "      WARNING: steamos-readonly failed - skipping system bundle"
fi

# Also remove ~/ca.crt if it exists
[ -f "$HOME/ca.crt" ] && rm "$HOME/ca.crt" && echo "      Removed ~/ca.crt"

# ---------------------------------------------------------------------------
# [2/3] Remove CA from Wine/Proton registry
# ---------------------------------------------------------------------------
echo "[2/3] Removing CA from Wine/Proton registry..."

WPREFIX=$(find_wineprefix || true)
WINE=$(find_wine || true)

if [ -z "$WPREFIX" ] || [ -z "$WINE" ]; then
    echo "      WARNING: Could not find wineprefix or wine binary - skipping registry cleanup."
else
    echo "      Prefix : $WPREFIX"
    echo "      Wine   : $WINE"
    export WINEPREFIX="$WPREFIX"

    python3 << PYEOF
import glob, os, re, subprocess, sys

wine    = "$WINE"
wprefix = "$WPREFIX"
env     = dict(os.environ, WINEPREFIX=wprefix)
wineboot = os.path.join(os.path.dirname(wine), "wineboot")

# Find the CA fingerprint from the registry files
fp = None
for reg_file in [os.path.join(wprefix, "system.reg"), os.path.join(wprefix, "user.reg")]:
    if not os.path.exists(reg_file):
        continue
    with open(reg_file, "r", encoding="utf-8", errors="surrogateescape") as f:
        text = f.read()
    # Look for our cert key pattern
    m = re.search(r"Software\\\\Microsoft\\\\SystemCertificates\\\\(?:Root|CA)\\\\Certificates\\\\([0-9A-Fa-f]{40})", text)
    if m:
        fp = m.group(1).upper()
        break

if not fp:
    print("      No proxy CA fingerprint found in registry, skipping.")
    sys.exit(0)

print(f"      Fingerprint: {fp}")

# Remove registry keys via wine reg delete
for hive, store_name in [("HKLM", "Root"), ("HKLM", "CA"), ("HKCU", "Root"), ("HKCU", "CA")]:
    key = rf"{hive}\Software\Microsoft\SystemCertificates\{store_name}\Certificates\{fp}"
    r = subprocess.run([wine, "reg", "delete", key, "/f"], env=env, capture_output=True, text=True)
    if r.returncode == 0:
        print(f"      Deleted: {key}")
    else:
        print(f"      Not found or already gone: {key}")

# Also scrub the .reg files directly for any residual blobs
for reg_file in [os.path.join(wprefix, "system.reg"), os.path.join(wprefix, "user.reg")]:
    if not os.path.exists(reg_file):
        continue
    with open(reg_file, "r", encoding="utf-8", errors="surrogateescape") as f:
        content = f.read()
    pattern = re.compile(
        rf"^\[Software\\\\Microsoft\\\\SystemCertificates\\\\(?:Root|CA)\\\\Certificates\\\\{fp}\]\n(?:.*\n)*?(?=^\[|\Z)",
        re.MULTILINE,
    )
    cleaned, n = pattern.subn("", content)
    if n:
        with open(reg_file, "w", encoding="utf-8", errors="surrogateescape") as f:
            f.write(cleaned)
        print(f"      Scrubbed {n} block(s) from {os.path.basename(reg_file)}")

boot_cmd = [wineboot, "-u"] if os.path.exists(wineboot) else [wine, "wineboot", "-u"]
subprocess.run(boot_cmd, env=env, capture_output=True, text=True)
print("      Wine registry reloaded.")
PYEOF
fi

# ---------------------------------------------------------------------------
# [3/3] Restore DNS
# ---------------------------------------------------------------------------
echo "[3/3] Restoring DNS to automatic..."
WIFI_IFACE=$(nmcli -t -f NAME,TYPE con show --active 2>/dev/null | grep ":wifi$" | cut -d: -f1 | head -1 || true)
[ -z "$WIFI_IFACE" ] && WIFI_IFACE=$(nmcli -t -f NAME con show --active 2>/dev/null | head -1 | cut -d: -f1 || true)

if [ -n "$WIFI_IFACE" ]; then
    nmcli con mod "$WIFI_IFACE" ipv4.dns "" ipv4.ignore-auto-dns no
    nmcli con up "$WIFI_IFACE"
    echo "      DNS restored (auto) on: $WIFI_IFACE"
else
    echo "      WARNING: No active connection found, DNS not changed."
fi

echo ""
echo "=== Uninstall complete! ==="
