# uninstall_cert_windows.ps1 - Remove Mad Max proxy CA from Windows
# Generated by madmax-2015-offline @ __LAN_IP__
#
# Usage (run in PowerShell as Administrator):
#   Set-ExecutionPolicy Bypass -Scope Process
#   Invoke-WebRequest http://__LAN_IP__:__HTTP_PORT__/provision/windows/uninstall -OutFile uninstall_cert_windows.ps1; .\uninstall_cert_windows.ps1

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

Write-Host "=== Mad Max - Windows Certificate Removal ===" -ForegroundColor Cyan

$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).
    IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    throw "Run this script as Administrator."
}

# ---------------------------------------------------------------------------
# [1/2] Remove CA certificate from Windows Root store
# ---------------------------------------------------------------------------
Write-Host "[1/2] Removing CA certificate from Windows Root store..."

# Find certs issued by our proxy CA (CN matching localproxy or issued to our domains)
$removed = 0
$candidates = Get-ChildItem Cert:\LocalMachine\Root | Where-Object {
    $_.Issuer -like "*localproxy*" -or
    $_.Subject -like "*localproxy*" -or
    $_.Issuer -like "*hydra.agoragames*" -or
    $_.Subject -like "*hydra.agoragames*" -or
    $_.Issuer -like "*psn.turbine*" -or
    $_.Subject -like "*psn.turbine*"
}

if ($candidates) {
    foreach ($cert in $candidates) {
        Write-Host "      Removing: $($cert.Subject) [$($cert.Thumbprint)]"
        $store = New-Object System.Security.Cryptography.X509Certificates.X509Store(
            [System.Security.Cryptography.X509Certificates.StoreName]::Root,
            [System.Security.Cryptography.X509Certificates.StoreLocation]::LocalMachine
        )
        $store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadWrite)
        $store.Remove($cert)
        $store.Close()
        $removed++
    }
    Write-Host "      Removed $removed certificate(s)."
} else {
    Write-Host "      No proxy CA certificates found in LocalMachine\Root."
}

# Clean up temp cert file if it exists
$certPath = "$env:TEMP\localproxy_ca.crt"
if (Test-Path $certPath) {
    Remove-Item $certPath -Force
    Write-Host "      Removed temp file: $certPath"
}

# ---------------------------------------------------------------------------
# [2/2] Restore DNS to automatic
# ---------------------------------------------------------------------------
Write-Host "[2/2] Restoring DNS to automatic..."

$defaultRoute = Get-NetRoute -AddressFamily IPv4 -DestinationPrefix "0.0.0.0/0" |
    Sort-Object RouteMetric, InterfaceMetric |
    Select-Object -First 1

if ($defaultRoute) {
    $adapter = Get-NetAdapter -InterfaceIndex $defaultRoute.InterfaceIndex -ErrorAction SilentlyContinue
    if ($adapter -and $adapter.Status -eq "Up") {
        Set-DnsClientServerAddress -InterfaceIndex $adapter.InterfaceIndex -ResetServerAddresses
        Write-Host "      DNS reset to automatic on: $($adapter.Name)"
    } else {
        Write-Host "      WARNING: Could not find active adapter, DNS not changed."
    }
} else {
    Write-Host "      WARNING: No default route found, DNS not changed."
}

Write-Host ""
Write-Host "=== Uninstall complete! ===" -ForegroundColor Green
