#!/usr/bin/env bash
# uninstall_service_deck.sh - Remove madmax-offline systemd service from Steam Deck
# Generated by madmax-2015-offline @ __LAN_IP__
#
# Usage (must be run as root):
#   curl -o uninstall_service_deck.sh http://__LAN_IP__:__HTTP_PORT__/provision/deck/service/uninstall && sudo bash uninstall_service_deck.sh

set -euo pipefail

SERVICE_NAME="madmax-offline"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
POLKIT_RULE="/etc/polkit-1/rules.d/50-${SERVICE_NAME}.rules"

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: Run this script with sudo." >&2
    exit 1
fi

echo "=== Mad Max Offline - Service Removal ==="

# ---------------------------------------------------------------------------
# [1/4] Stop and disable the service
# ---------------------------------------------------------------------------
echo "[1/4] Stopping and disabling service..."

if systemctl is-active --quiet "${SERVICE_NAME}" 2>/dev/null; then
    systemctl stop "${SERVICE_NAME}"
    echo "      Service stopped."
else
    echo "      Service was not running."
fi

if systemctl is-enabled --quiet "${SERVICE_NAME}" 2>/dev/null; then
    systemctl disable "${SERVICE_NAME}"
    echo "      Service disabled."
else
    echo "      Service was not enabled."
fi

# ---------------------------------------------------------------------------
# [2/4] Remove the unit file
# ---------------------------------------------------------------------------
echo "[2/4] Removing service file..."

steamos-readonly disable 2>/dev/null || true

if [ -f "${SERVICE_FILE}" ]; then
    rm "${SERVICE_FILE}"
    systemctl daemon-reload
    echo "      Removed: ${SERVICE_FILE}"
else
    echo "      Not found: ${SERVICE_FILE}, skipping."
fi

# ---------------------------------------------------------------------------
# [3/4] Remove the polkit rule
# ---------------------------------------------------------------------------
echo "[3/4] Removing polkit rule..."

if [ -f "${POLKIT_RULE}" ]; then
    rm "${POLKIT_RULE}"
    echo "      Removed: ${POLKIT_RULE}"
else
    echo "      Not found: ${POLKIT_RULE}, skipping."
fi

steamos-readonly enable 2>/dev/null || true

# ---------------------------------------------------------------------------
# [4/4] Restore DNS to automatic
# ---------------------------------------------------------------------------
echo "[4/4] Restoring DNS to automatic..."

CONN=$(nmcli -t -f NAME,TYPE con show --active 2>/dev/null | grep ":wifi$" | cut -d: -f1 | head -1 || true)
[ -z "$CONN" ] && CONN=$(nmcli -t -f NAME con show --active 2>/dev/null | head -1 | cut -d: -f1 || true)

if [ -n "$CONN" ]; then
    nmcli con mod "$CONN" ipv4.dns "" ipv4.ignore-auto-dns no
    nmcli con up "$CONN"
    echo "      DNS restored (auto) on: $CONN"
else
    echo "      WARNING: No active connection found, DNS not changed."
fi

echo ""
echo "=== Removal complete! ==="
echo ""
echo "The madmax-offline service and polkit rule have been fully removed."
echo "If you also want to remove the CA certificate, run:"
echo "  curl -o uninstall_cert_deck.sh http://__LAN_IP__:__HTTP_PORT__/provision/deck/uninstall && bash uninstall_cert_deck.sh"
